<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Decision Advocacy Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Decision Advocacy Challenge</h1>
<p class="subtitle lead">Data-Driven Scheduling for Maximum Productivity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="decision-advocacy-challenge---patricks-auto-shop-analysis" class="level1">
<h1>🔧 Decision Advocacy Challenge - Patrick’s Auto Shop Analysis</h1>
<section id="the-business-problem" class="level2">
<h2 class="anchored" data-anchor-id="the-business-problem">The Business Problem 🎯</h2>
<p>Patrick runs a network of 5 auto repair shops. He’s been tracking productivity data (number of cars fixed per day) across all shops, along with whether he (the boss) was present at each shop on each day.</p>
<p><strong>The Core Question:</strong> When and where should Patrick schedule his presence to maximize productivity and revenue?</p>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data 📊</h2>
<p>The dataset contains 250 observations of daily productivity across 5 shops:</p>
<div class="cell" data-execution_count="2">
<div id="tbl-data-overview" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-data-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Overview of the productivity data
</figcaption>
<div aria-describedby="tbl-data-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="186">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">observation</th>
<th data-quarto-table-cell-role="th">shopID</th>
<th data-quarto-table-cell-role="th">boss</th>
<th data-quarto-table-cell-role="th">carsFixed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>1</td>
<td>0</td>
<td>8</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>2</td>
<td>0</td>
<td>22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>3</td>
<td>0</td>
<td>32</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>4</td>
<td>1</td>
<td>64</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>5</td>
<td>0</td>
<td>53</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>1</td>
<td>1</td>
<td>21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>2</td>
<td>0</td>
<td>20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>3</td>
<td>0</td>
<td>42</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>4</td>
<td>0</td>
<td>31</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>5</td>
<td>0</td>
<td>55</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-execution_count="3">
<div id="tbl-data-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-data-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Summary statistics by shop and boss presence
</figcaption>
<div aria-describedby="tbl-data-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="187">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">shopID</th>
<th data-quarto-table-cell-role="th">boss</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th rowspan="2" data-quarto-table-cell-role="th" data-valign="top">1</th>
<th data-quarto-table-cell-role="th">0</th>
<td>40</td>
<td>11.05</td>
<td>2.93</td>
<td>5</td>
<td>17</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>10</td>
<td>18.00</td>
<td>3.13</td>
<td>13</td>
<td>23</td>
</tr>
<tr class="odd">
<th rowspan="2" data-quarto-table-cell-role="th" data-valign="top">2</th>
<th data-quarto-table-cell-role="th">0</th>
<td>45</td>
<td>22.13</td>
<td>4.82</td>
<td>11</td>
<td>35</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>32.20</td>
<td>2.59</td>
<td>29</td>
<td>35</td>
</tr>
<tr class="odd">
<th rowspan="2" data-quarto-table-cell-role="th" data-valign="top">3</th>
<th data-quarto-table-cell-role="th">0</th>
<td>35</td>
<td>32.46</td>
<td>5.59</td>
<td>23</td>
<td>49</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>15</td>
<td>35.40</td>
<td>5.00</td>
<td>25</td>
<td>44</td>
</tr>
<tr class="odd">
<th rowspan="2" data-quarto-table-cell-role="th" data-valign="top">4</th>
<th data-quarto-table-cell-role="th">0</th>
<td>45</td>
<td>37.02</td>
<td>5.61</td>
<td>26</td>
<td>51</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>5</td>
<td>49.80</td>
<td>10.08</td>
<td>39</td>
<td>64</td>
</tr>
<tr class="odd">
<th rowspan="2" data-quarto-table-cell-role="th" data-valign="top">5</th>
<th data-quarto-table-cell-role="th">0</th>
<td>35</td>
<td>45.51</td>
<td>7.24</td>
<td>32</td>
<td>60</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>15</td>
<td>53.73</td>
<td>5.31</td>
<td>45</td>
<td>62</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="productivity-by-shop-and-boss-presence" class="level2">
<h2 class="anchored" data-anchor-id="productivity-by-shop-and-boss-presence">Productivity by shop and boss presence</h2>
<div id="e9f1eb1d" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-1.png" width="951" height="567" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Analysis of Cars Fixed per Day by Boss Presence</strong></p>
<p>What this plot shows:</p>
<ul>
<li><strong>General Trend:</strong> You can observe two distinct clusters of data points for each ‘Boss Presence’ category. The cluster for ‘Present’ (green dots) is generally higher on the ‘Number of Cars Fixed’ axis than the cluster for ‘Absent’ (red dots).</li>
<li><strong>Increased Productivity:</strong> This visually confirms that, on average, more cars tend to be fixed when Patrick is present compared to when he is absent.</li>
<li><strong>Spread of Data:</strong> The spread of the dots within each category indicates the variability in cars fixed. Even when Patrick is present, there’s a range of productivity, and similarly when he’s absent. However, the overall shift upwards when he’s there is quite apparent.</li>
</ul>
<p>This plot effectively illustrates the moderate positive correlation, providing a clear visual representation of how Patrick’s presence impacts the daily number of cars fixed.</p>
<div id="ecbb9837" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-6-output-1.png" width="615" height="375" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="04636988" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>The correlation between 'boss presence' and 'carsFixed' is: 0.2738
There is a moderate positive correlation, suggesting that boss presence is associated with a noticeable increase in cars fixed.</code></pre>
</div>
</div>
<p><strong>Productivity per shop and boss presence</strong></p>
<div id="8c2d079f" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>Mean Productivity per Shop:</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">boss</th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">shopID</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1</th>
<td>11.05</td>
<td>18.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2</th>
<td>22.13</td>
<td>32.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">3</th>
<td>32.46</td>
<td>35.40</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>37.02</td>
<td>49.80</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">5</th>
<td>45.51</td>
<td>53.73</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="441197c3" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-9-output-1.png" width="722" height="567" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Overall Best Performing Shop:</strong></p>
<p><strong>Shop 5:</strong> Consistently fixes the highest number of cars, both when Patrick is absent (45.51 cars) and when he is present (53.73 cars). While Patrick’s presence still adds to its productivity, Shop 5 has the highest baseline and overall output.</p>
<p><strong>Overall Worst Performing Shop:</strong></p>
<p><strong>Shop 1:</strong> Consistently fixes the lowest number of cars, both when Patrick is absent (11.05 cars) and when he is present (18.00 cars). It has the lowest baseline productivity among all shops.</p>
<p><strong>Shops that benefit MOST from Patrick’s Presence (where his presence makes the biggest positive difference):</strong></p>
<p><strong>Shop 4:</strong> This shop shows the largest percentage increase and absolute increase (12.78 additional cars) when Patrick is present. His visits have the most significant impact on boosting its productivity. <strong>Shop 2:</strong> Also benefits greatly from Patrick’s presence (10.07 additional cars).</p>
<p><strong>Shop that benefits LEAST from Patrick’s Presence (where his presence makes the smallest positive difference):</strong></p>
<p><strong>Shop 3:</strong> While productivity still increases with Patrick’s presence, the impact is the smallest (2.94 additional cars) compared to other shops. This means his time there yields the least additional output relative to the other locations.</p>
<p><strong>In summary, Shop 5 is your top performer in absolute terms, while Shop 1 is the lowest. However, if Patrick wants to maximize the impact of his presence, he should prioritize Shop 4 and Shop 2, as his visits there lead to the most substantial increases in cars fixed.</strong></p>
<p><strong>Recommendations: Which shops should he prioritize? Why?</strong></p>
<p>Based on our detailed analysis, here are the clear, specific recommendations for Patrick’s shop prioritization:</p>
<p><strong>Which shops should he prioritize?</strong></p>
<p>Patrick should prioritize visiting <strong>Shop 4</strong>, followed by <strong>Shop 2</strong>, and then <strong>Shop 5</strong>.</p>
<p><strong>Why?</strong></p>
<ul>
<li><p><strong>Shop 4 (Highest Impact):</strong> Patrick’s presence at Shop 4 yields the most significant increase in productivity, adding an average of <strong>12.78</strong> more cars fixed per day. This is where his time makes the biggest difference to the total number of cars fixed across the network.</p></li>
<li><p><strong>Shop 2 (Second Highest Impact):</strong> His presence in Shop 2 also leads to a substantial boost, with an average increase of <strong>10.07</strong> additional cars fixed per day.</p></li>
<li><p><strong>Shop 5 (Strong Performer):</strong> Even though Shop 5 is already the highest performing shop overall (with or without him), his presence still adds a considerable <strong>8.22</strong> additional cars, making it a valuable place to visit.</p></li>
</ul>
<p><strong>Conversely, which shops should he reconsider prioritizing?</strong></p>
<p>Patrick should reconsider frequent visits to <strong>Shop 3</strong> if maximizing network productivity is the primary goal. While his presence there is still positive, it results in the smallest average increase of only <strong>2.94</strong> additional cars fixed per day. This means his time spent at Shop 3 yields the least additional output compared to the other locations. Spending more time at Shops 4, 2, and 5 would offer a much greater return on his valuable time.</p>
</section>
<section id="potential-financial-impact-total-weekly-revenue-from-top-shops" class="level2">
<h2 class="anchored" data-anchor-id="potential-financial-impact-total-weekly-revenue-from-top-shops">Potential Financial Impact: Total Weekly Revenue from Top Shops</h2>
<p>Let’s calculate the total potential weekly revenue impact for the top shops. Based on our analysis, the shops where Patrick’s presence has the most significant impact are Shop 4, Shop 2, and Shop 5.</p>
<p>Assuming an average revenue of <strong>$500 per car fixed</strong>, and considering that Patrick can visit one shop per day, if he dedicates one day each to these three top-impact shops within a week, the calculations are as follows:</p>
<ul>
<li><strong>Shop 4 Impact:</strong> 12.78 additional cars/day * $500/car = <strong>$6,390 additional revenue for that day</strong></li>
<li><strong>Shop 2 Impact:</strong> 10.07 additional cars/day * $500/car = <strong>$5,035 additional revenue for that day</strong></li>
<li><strong>Shop 5 Impact:</strong> 8.22 additional cars/day * $500/car = <strong>$4,110 additional revenue for that day</strong></li>
</ul>
<p><strong>Total Weekly Revenue Impact (from visiting these three high-impact shops once each in a week):</strong></p>
<p>$6,390 (Shop 4) + $5,035 (Shop 2) + $4,110 (Shop 5) = <strong>$15,535</strong></p>
<p>Therefore, by strategically allocating just three days of his week to these three high-impact shops, Patrick could potentially generate an <strong>additional $15,535 in revenue per week</strong> for the network. This clearly demonstrates the significant financial incentive behind optimized scheduling.</p>
</section>
<section id="confidence-assessment-for-revenue-figures" class="level2">
<h2 class="anchored" data-anchor-id="confidence-assessment-for-revenue-figures">Confidence Assessment for Revenue Figures</h2>
<p>Let’s talk about how confident we can be in these revenue figures. Remember, these are projections based on historical data, and it’s important to understand the factors that influence their accuracy:</p>
<p><strong>1. Data Limitations – Not a Crystal Ball:</strong></p>
<ul>
<li><strong>Limited Historical Data:</strong> Our calculations are based on 250 days of data. While helpful, this isn’t a massive dataset. When we break it down by individual shops and whether you were present or not, the number of observations for each specific scenario becomes even smaller (e.g., only 5 or 10 days of your presence at some shops).</li>
<li><strong>Averages as Best Guesses:</strong> The ‘additional cars fixed’ numbers (like 12.78 for Shop 4) are averages. They are our best estimates based on the available data, but individual days will naturally vary. On any given day, the actual increase could be a bit higher or lower than the average.</li>
</ul>
<p><strong>2. Key Assumptions We’re Making:</strong></p>
<ul>
<li><strong>Past Predicts Future:</strong> We’re assuming that the patterns observed in the past 250 days will continue. If there are significant changes in staffing, equipment, local market conditions, or even your management style, the results might differ.</li>
<li><strong>Direct Causation:</strong> We’re attributing the increase directly to your presence. While the correlation is clear, the data doesn’t tell us <em>why</em> your presence helps. It could be due to your direct supervision, problem-solving, improved morale, or other factors that happen concurrently with your visits.</li>
<li><strong>Fixed Revenue per Car:</strong> We’ve used an assumed $500 revenue per car. If your actual revenue per car varies, or if the mix of services changes, the financial impact will shift accordingly.</li>
</ul>
<p><strong>3. Potential Variability and Uncertainty:</strong></p>
<ul>
<li><strong>Day-to-Day Fluctuations:</strong> Just because Shop 4 averages a 12.78-car increase doesn’t mean it will be exactly that every time you visit. Some days it might be 10, other days 15. The revenue figure is an average projection.</li>
<li><strong>External Factors:</strong> Unforeseen events like major car recalls, economic downturns, or even severe weather could impact overall productivity and revenue, regardless of your schedule.</li>
</ul>
<p><strong>In summary:</strong> The revenue figures are strong, data-driven <em>estimates</em> that highlight the <em>potential</em> financial gains from optimized scheduling. They provide a very solid basis for making strategic decisions. However, they should be viewed with a realistic understanding that real-world outcomes can vary due to factors not fully captured in the historical data or our assumptions. Continuous monitoring and adjustment would be wise.</p>
<div id="ea147fab" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-10-output-1.png" width="763" height="471" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="potential-additional-weekly-revenue-from-top-shops" class="level2">
<h2 class="anchored" data-anchor-id="potential-additional-weekly-revenue-from-top-shops">Potential Additional Weekly Revenue from Top Shops</h2>
<p>Let’s visualize the potential weekly revenue impact for the top shops (Shop 4, Shop 2, and Shop 5). This bar plot will show the estimated additional revenue generated by Patrick’s presence at each of these high-impact locations.</p>
<p>The bar plot showing the ‘Potential Additional Weekly Revenue from Top Shops’ has been successfully generated! You might have seen a FutureWarning from Seaborn, but the plot is correct.</p>
<p>This chart clearly illustrates the significant financial gains that can be achieved by strategically prioritizing Patrick’s visits:</p>
<ul>
<li><strong>Shop 4:</strong> Stands out with the highest potential additional weekly revenue of <strong>$6,390</strong> from a single day’s visit, reinforcing its status as the most impactful shop.</li>
<li><strong>Shop 2:</strong> Follows with a strong potential of <strong>$5,035</strong> in additional weekly revenue.</li>
<li><strong>Shop 5:</strong> Also contributes a substantial <strong>$4,110</strong> in additional weekly revenue.</li>
</ul>
<p>This visualization powerfully demonstrates the financial incentive for Patrick to allocate his time to these specific high-impact shops, as it directly translates into thousands of dollars in additional revenue per week for the business.</p>
<div id="b388ebe4" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-11-output-1.png" width="1141" height="663" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="projected-outcomes-under-different-scheduling-scenarios" class="level2">
<h2 class="anchored" data-anchor-id="projected-outcomes-under-different-scheduling-scenarios">Projected Outcomes Under Different Scheduling Scenarios</h2>
<p>This chart clearly shows the ‘Total Cars Fixed’ for each potential scheduling scenario, making it easy to compare the impact of various choices.</p>
<p>The bar plot visualizing ‘Projected Total Cars Fixed per Day Under Different Scheduling Scenarios’ has been successfully generated! You might have noticed a FutureWarning from Seaborn, but the plot is correct and clearly illustrates the outcomes.</p>
<p>This chart effectively summarizes the potential impact of different scheduling choices for Patrick:</p>
<ul>
<li><strong>Highest Productivity:</strong> The scenario ‘Patrick visits Shop 4’ consistently yields the highest total number of cars fixed across the network, demonstrating the maximum potential productivity.</li>
<li><strong>Next Best:</strong> Visiting Shop 2 and Shop 5 also results in significantly higher total cars fixed compared to Patrick being absent everywhere, indicating these are also high-impact shops.</li>
<li><strong>Lowest Productivity:</strong> The ‘Patrick Absent Everywhere’ scenario results in the lowest total number of cars fixed, serving as a baseline of productivity without his presence.</li>
<li><strong>Least Impactful Visit:</strong> While still an improvement, ‘Patrick visits Shop 3’ shows the smallest increase in total cars fixed, suggesting his time there is less impactful on overall network productivity compared to other shops.</li>
</ul>
<p>This visualization powerfully reinforces the strategic importance of Patrick’s scheduling decisions in maximizing the total number of cars fixed.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>